export const INPUT_FOCUS = 'header/INPUT_FOCUS'
export const INPUT_BLUR = 'header/INPUT_BLUR'
export const CHANGE_LIST ='header/CHANGE_LIST'
export const MOUNSE_ENTER ='header/MOUNSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'